package com.redhat;


import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;
import org.apache.camel.component.kafka.KafkaComponent;
import org.apache.camel.Processor;
import org.apache.camel.Exchange;


/**
 * Generated from Swagger specification by Camel REST DSL generator.
 */


public final class CreditChargeCard extends RouteBuilder {
    /**
     * Defines Apache Camel routes using REST DSL fluent API.
     */
    public void configure() {

       String kafkaBootstrap = "my-cluster-kafka-brokers.dm-kafka.svc.cluster.local:9092";


        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .post("/credit-charge-card/activation")
                .id("activateSDCreditChargeCard")
                .description("Activate  a  SDCreditChargeCard servicing session")
                .produces("application/json")
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SDCreditChargeCard Request Payload")
                .endParam()
                .to("direct:activateSDCreditChargeCard")
                .put("/credit-charge-card/{sd-reference-id}/configuration")
                .id("configureSDCreditChargeCard")
                .description("Update an active SDCreditChargeCard session configuration")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SDCreditChargeCard Servicing Session Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SDCreditChargeCard Configure Request Payload")
                .endParam()
                .to("direct:configureSDCreditChargeCard");
        ;
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .put("/credit-charge-card/{sd-reference-id}/feedback")
                .id("feedbackSDCreditChargeCard")
                .description("Capturing feedback against the SDCreditChargeCard service that can target different levels of detail: SD/CR/BQ")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SDCreditChargeCard Servicing Session Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SDCreditChargeCard Feedback Request Payload")
                .endParam()
                .to("direct:feedbackSDCreditChargeCard")
                .get("/credit-charge-card/{sd-reference-id}")
                .id("retrieveSDCreditChargeCard")
                .description("Analytical views maintained by the SDCreditChargeCard service center for management reporting and analysis purposes")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SDCreditChargeCard Servicing Session Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/SDCreditChargeCardRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveSDCreditChargeCard")
                .post("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/initiation")
                .id("initiateCreditChargeCardFulfilmentArrangement")
                .description("a new card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CreditChargeCardFulfilmentArrangement Request Payload")
                .endParam()
                .to("direct:initiateCreditChargeCardFulfilmentArrangement")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangement")
                .description("details about a card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangement");
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/control")
                .id("controlCreditChargeCardFulfilmentArrangementUpdate")
                .description("the processing of a card account (e.g. suspend)")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Request Payload")
                .endParam()
                .to("direct:controlCreditChargeCardFulfilmentArrangementUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}")
                .id("retrieveCreditChargeCard")
                .description("details about a card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/CRCreditChargeCardFulfilmentArrangementRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCard")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/interest/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementInterest")
                .description("details about interest accrued to an account .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Interest Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQInterestRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementInterest")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/servicefees/{bq-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangementServiceFees")
                .description("a fee transaction applied to a card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ServiceFees Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("ServiceFees Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangementServiceFees")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/servicefees/{bq-reference-id}/execution")
                .id("executeCreditChargeCardFulfilmentArrangementServiceFeesUpdate")
                .description("fees to a card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ServiceFees Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("ServiceFees request payload")
                .endParam()
                .to("direct:executeCreditChargeCardFulfilmentArrangementServiceFeesUpdate")
        ;
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/servicefees/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementServiceFees")
                .description("details about fees applied to an account .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ServiceFees Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQServiceFeesRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementServiceFees")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/billing/{bq-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangementBilling")
                .description("details of a billing transaction (invoice)")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Billing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Billing Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangementBilling")
        ;
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/billing/{bq-reference-id}/execution")
                .id("executeCreditChargeCardFulfilmentArrangementBillingUpdate")
                .description("the billing process for a card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Billing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Billing request payload")
                .endParam()
                .to("direct:executeCreditChargeCardFulfilmentArrangementBillingUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/billing/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementBilling")
                .description("details about a billing process for a card account .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Billing Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQBillingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementBilling")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/repayment/{bq-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangementRepayment")
                .description("a repayment transaction (bill payment)")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Repayment Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Repayment Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangementRepayment")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/repayment/{bq-reference-id}/execution")
                .id("executeCreditChargeCardFulfilmentArrangementRepaymentUpdate")
                .description("a repayment transaction against the card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Repayment Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Repayment request payload")
                .endParam()
                .to("direct:executeCreditChargeCardFulfilmentArrangementRepaymentUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/repayment/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementRepayment")
                .description("detail about a repayment transaction .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Repayment Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQRepaymentRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementRepayment")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/cardtransaction/{bq-reference-id}/exchange")
                .id("exchangeCreditChargeCardFulfilmentArrangementCardTransactionUpdate")
                .description("accept etc. a card account transaction")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CardTransaction Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CardTransaction request payload")
                .endParam()
                .to("direct:exchangeCreditChargeCardFulfilmentArrangementCardTransactionUpdate")
        ;
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/cardtransaction/{bq-reference-id}/execution")
                .id("executeCreditChargeCardFulfilmentArrangementCardTransactionUpdate")
                .description("a card account transaction")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CardTransaction Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CardTransaction request payload")
                .endParam()
                .to("direct:executeCreditChargeCardFulfilmentArrangementCardTransactionUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/cardtransaction/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementCardTransaction")
                .description("details about a card account transaction .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CardTransaction Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQCardTransactionRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementCardTransaction")
                .post("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/issueddevice/initiation")
                .id("initiateCreditChargeCardFulfilmentArrangementIssuedDevice")
                .description("a type of device for the card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Request Payload")
                .endParam()
                .to("direct:initiateCreditChargeCardFulfilmentArrangementIssuedDevice")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/issueddevice/{bq-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangementIssuedDevice")
                .description("details about an issued device")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("IssuedDevice Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("IssuedDevice Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangementIssuedDevice")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/issueddevice/{bq-reference-id}/exchange")
                .id("exchangeCreditChargeCardFulfilmentArrangementIssuedDeviceUpdate")
                .description("reject, verify etc. an issued device")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("IssuedDevice Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("IssuedDevice request payload")
                .endParam()
                .to("direct:exchangeCreditChargeCardFulfilmentArrangementIssuedDeviceUpdate")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/issueddevice/{bq-reference-id}/requisition")
                .id("requestCreditChargeCardFulfilmentArrangementIssuedDeviceUpdate")
                .description("the issuance of a device (e.g. a new card)")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("IssuedDevice Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("IssuedDevice request payload")
                .endParam()
                .to("direct:requestCreditChargeCardFulfilmentArrangementIssuedDeviceUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/issueddevice/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementIssuedDevice")
                .description("details about an issued device .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("IssuedDevice Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQIssuedDeviceRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementIssuedDevice")
                .post("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/creditplan/initiation")
                .id("initiateCreditChargeCardFulfilmentArrangementCreditPlan")
                .description("a credit plan linked to the card account")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Request Payload")
                .endParam()
                .to("direct:initiateCreditChargeCardFulfilmentArrangementCreditPlan")
        ;
        rest("/sd-credit-chrg-card/credit-charge-cardv2")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/creditplan/{bq-reference-id}/update")
                .id("updateCreditChargeCardFulfilmentArrangementCreditPlan")
                .description("details of the credit plan")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CreditPlan Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CreditPlan Request Payload")
                .endParam()
                .to("direct:updateCreditChargeCardFulfilmentArrangementCreditPlan")
                .put("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/creditplan/{bq-reference-id}/requisition")
                .id("requestCreditChargeCardFulfilmentArrangementCreditPlanUpdate")
                .description("manual intervention with a credit plan")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CreditPlan Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CreditPlan request payload")
                .endParam()
                .to("direct:requestCreditChargeCardFulfilmentArrangementCreditPlanUpdate")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/creditplan/{bq-reference-id}/")
                .id("retrieveCreditChargeCardFulfilmentArrangementCreditPlan")
                .description("details about a linked credit plan .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("CreditPlan Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQCreditPlanRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCreditChargeCardFulfilmentArrangementCreditPlan")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement")
                .id("RetrieveCreditChargeCardReferenceIds")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("collection-filter")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Filter to refine the result set. ex- CreditChargeCard Instance Status='active'")
                .endParam()
                .to("direct:RetrieveCreditChargeCardReferenceIds")
                .get("/credit-charge-card/credit-charge-card-fulfilment-arrangement/behavior-qualifiers/")
                .id("RetrieveCreditChargeCardBehaviorQualifiers")
                .produces("application/json")
                .to("direct:RetrieveCreditChargeCardBehaviorQualifiers")
                .get("/credit-charge-card/{sd-reference-id}/credit-charge-card-fulfilment-arrangement/{cr-reference-id}/{behavior-qualifier}/")
                .id("RetrieveCreditChargeCardBehaviorQualifierReferenceIds")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Credit Charge Card Fulfilment Arrangement Instance Reference")
                .endParam()
                .param()
                .name("behavior-qualifier")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Behavior Qualifier Name. ex- CreditPlan")
                .endParam()
                .param()
                .name("collection-filter")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Filter to refine the result set. ex- CreditPlan Instance Status = 'pending'")
                .endParam()
                .to("direct:RetrieveCreditChargeCardBehaviorQualifierReferenceIds");

        rest("/sd-credit-chrg-card/credit-charge-card")
                .put("/credit-charge-card/{sdreferenceid}/credit-charge-card-fulfilment-arrangement/{crreferenceid}/cardtransaction/{bqreferenceid}/update")
                .route()
                .log("${header.sdreferenceid}")
                .setHeader("kafka.KEY",simple("${header.sdreferenceid}"))
                .to("kafka:"+"credit-charge-card"+ "?brokers=" + kafkaBootstrap);

    }


    private final class ProcessEvents implements Processor {


        @Override
        public void process(Exchange exchange) throws Exception {
            com.fasterxml.jackson.databind.ObjectMapper mapper = new com.fasterxml.jackson.databind.ObjectMapper();
            exchange.getIn().setBody(mapper.writeValueAsString(exchange.getIn().getBody()));

        }
        }
}
